### ISSUE TITLE
Installer bombs

### ISSUE THREAD

**Issue by DarkBlaez** [Minds/minds#102] opened 2018-05-02 20:58 UTC
Followed instructions. Using a VM with docker plus Ubuntu 16.04. Everything works up to this point.

Run the installer and bombs....

installer_1      | cli.php: [EXCEPTION:ErrorException] stream_socket_client(): unable to connect to tcp://localhost:5672 (Address not available)
minds_installer_1 exited with code 1

Is there a setting I need to change to point to the actual IP of the VM or I assume this is internal to the host so should be localhost?

**Comment by markharding** [comment] 2018-05-02 21:03
This is a duplicate of #100 I think. The install would have worked, but there are some tweaks you will need to do the get the queue runners up and running. A fix by the community would be required here.

**Closed by markharding** 2018-05-02 21:03 UTC
