### ISSUE TITLE
gulp build has an error in build.sass

### ISSUE THREAD

**Issue by 4nanook** [Minds/minds#50] opened 2017-06-24 10:26 UTC
10:24:06] Starting 'build.sass'...
Error in plugin 'sass'
Message:
    app/stylesheets/components/mature.scss
Error: Undefined variable: "$minds-padding".
        on line 128 of app/stylesheets/components/mature.scss
>>     top: $minds-padding;
   ---------^

[10:24:23] Finished 'build.sass' after 18 s

**Comment by markharding** [comment] 2017-06-26 08:29
Thanks, this is a duplicate of front/issues/17

**Closed by markharding** 2017-06-26 08:29 UTC
