### ISSUE TITLE
Challenge Issued

### ISSUE THREAD

**Issue by DarkBlaez** [Minds/minds#96] opened 2018-04-25 17:57 UTC
I'm issuing a challegne to the primary devs to perform a fresh install using the wiki as the guide or the docs. Having tried this as spelled out in both places there are numerous errors. Both with vagrant and/or performing a regular install. All one has to do is spin up a VM (they are super cheap) and provision another box, start from scratch. I have done this numerous times so there has to be some steps left out. Only through a fresh install will you see this. Many times developers keep pushing along with their boxes which are already configured but rarely attempt a fresh install on a new box to insure no loose ends exit. I contend that based on documentation and wiki that this is the case.

-DB

**Comment by kyphosis** [comment] 2018-04-25 17:59
#93

**Comment by DarkBlaez** [comment] 2018-04-25 18:02
Doesn't result in something operational. I posted an issue already around this. Again, clean install is the challenge.. refer to my issue opened under vagrant. Also, there should be steps posted for a native install which can be replicated in clean environments

**Comment by kyphosis** [comment] 2018-04-25 18:09
I referenced the issue because you can see from the issue people are working on improving the documentation.

**Comment by DarkBlaez** [comment] 2018-04-25 18:11
Gotcha... what focus is being given to perform a clean install?

As you can see in a fresh install vagrant up results in... 

    default: npm WARN rollback Rolling back rlp@2.0.0 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/var/www/Minds/engine/vendor/minds/mw3/node_modules/rlp/.nfs00000002006f55f600000002'
    default: npm WARN rollback Rolling back ethjs-signer@0.1.1 failed (this is probably harmless): EBUSY: resource busy or locked, unlink '/var/www/Minds/engine/vendor/minds/mw3/node_modules/ethjs-signer/.nfs00000002006f55f800000001'
    default: npm WARN mw3@0.0.1 No description
    default: npm ERR! path /var/www/Minds/engine/vendor/minds/mw3/node_modules/rlp/bin/rlp
    default: npm ERR! code
    default:  ENOENT
    default: npm ERR! errno -2
    default: npm ERR! syscall chmod
    default: npm ERR! enoent ENOENT: no such file or directory, chmod '/var/www/Minds/engine/vendor/minds/mw3/node_modules/rlp/bin/rlp'
    default: npm ERR! enoent This is related to npm not being able to find a file.
    default: npm ERR! enoent 
    default: npm ERR!
    default:  A complete log of this run can be found in:
    default: npm ERR!     /root/.npm/_logs/2018-04-25T18_09_26_367Z-debug.log
    default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
    default: Loading composer repositories with package information
    default: Installing dependencies (including require-dev) from lock file
    default: Nothing to install or update
    default: Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.
    default: Package graphaware/neo4j-response-formatter is abandoned, you should avoid using it. No replacement was suggested.
    default: Package neoxygen/neoclient is abandoned, you should avoid using it. Use graphaware/neo4j-php-client instead.
    default: Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.
    default: Generating autoload files
    default: /home/vagrant
    default: Installing Minds…
    default: PHP Warning:  mkdir(): File exists in /var/www/Minds/bin/regenerateDevKeys.php on line 13
    default: - Checking passed options: 
    default: 
    default: cli.php: [ERROR] Email private key path was not provided
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by ottman** [comment] 2018-04-25 18:13
Have you checked out the Docker flow in readme?

**Comment by DarkBlaez** [comment] 2018-04-25 18:15
Which one? there are a number of docker references in each repo for minds and the docs. Point me to it and I will check it out. Also, the latest docker-compose.yml tosses the entire thing in to a loop waiting/timing out

**Comment by kyphosis** [comment] 2018-04-25 18:25
@DarkBlaez i failed with clean install aswell.. docker, without docker, auto-install script, all with no luck,.

**Comment by DarkBlaez** [comment] 2018-04-25 18:27
@kyphosis This is why we need core devs to take the time to perform a clean install. This tends to be a recurring issue and I always have my own devs perform clean installs upn each release to insure nothing gets missed. Far to easy to get caught up on new enhancements and bug fixes, but some time should be dedicated to insuring a clean install works

**Comment by DarkBlaez** [comment] 2018-04-25 18:36
Even if you perform a docker-compose up, then reference the docker setup in the readme for the primary minds repo. When you get to this step

    docker exec -it CONTAINER_ID_HERE php /var/www/Minds/engine/cli.php install --graceful-storage-provision --domain=dev.minds.io --username=minds --password=password --email=minds@dev.minds.io --private-key=/.dev/minds.pem --public-key=/.dev/minds.pub --cassandra-server=cassandra

It blows chunks with:

- Checking passed options: 
cli.php: [ERROR] Email private key path was not provided

At this point we will need to wait for the core devs to do some due diligence to perform a clean install and document/fix this. If this is how the primary site is being run I cannot fathom what happens if there is a failure requiring a scratch rebuild versus using a backup

**Comment by DarkBlaez** [comment] 2018-04-25 18:41
Did that and that portion works fine and results in: Keys done /.dev/minds.pem

**Comment by kyphosis** [comment] 2018-04-25 18:41
Not sure, i'm getting errors even when i do that.

**Comment by DarkBlaez** [comment] 2018-04-25 18:44
For this to error out like it is under most of these mechanisms for install there are some issues with the scripts or something that has been missed. For a core dev to try this in a new environment should not take long and given their experience with the code base should not take them long to post some resolution for this quickly

**Comment by kyphosis** [comment] 2018-04-25 19:25
What steps did you take? Let me reproduce, didn't get that far.

**Comment by DarkBlaez** [comment] 2018-04-25 19:28
All I did was bring up the docker containers with docker-compose and then started going through the docker setup. But that failed. Again there seem to be script errors or things missing. All of this will take a core dev to look at. I ponder if this code base is fully functional, have not heard of anyone getting it up and operational from a clean implementation. Seems to be so many of these instances on github like this

**Comment by markharding** [comment] 2018-04-25 21:03
I'm going to close this so we condense all installation discussion to #93. We're going to be updating the docs this week.

**Closed by markharding** 2018-04-25 21:03 UTC
