### ISSUE TITLE
Where is source code socket

### ISSUE THREAD

**Issue by duythien** [Minds/minds#51] opened 2017-07-23 00:07 UTC
Hello,
I have see your code have connect a socket such as http://dev.minds.io:8010, but I was not see where is your code

Could you adding a information for this

Thanks

**Comment by markharding** [comment] 2017-07-23 12:40
We'll be release the socket repo soon, but it has some hard coded variables that need removing before we can make it public. Closing this as it's a duplicate of #21

**Closed by markharding** 2017-07-23 12:40 UTC

**Comment by duythien** [comment] 2017-07-24 03:19
Thanks
